-- AlterTable
ALTER TABLE "Pagar" ADD COLUMN     "estado" TEXT NOT NULL DEFAULT 'PENDIENTE',
ADD COLUMN     "fechaPago" TIMESTAMP(3),
ADD COLUMN     "metodoPago" TEXT NOT NULL DEFAULT 'TRANSFERENCIA',
ADD COLUMN     "referencia" TEXT;

-- AlterTable
ALTER TABLE "Trabajador" ADD COLUMN     "banco" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "estado" TEXT NOT NULL DEFAULT 'ACTIVO',
ADD COLUMN     "fechaContrato" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "metodoPago" TEXT NOT NULL DEFAULT 'TRANSFERENCIA',
ADD COLUMN     "numeroCuenta" TEXT,
ADD COLUMN     "telefono" TEXT;
